---
root: true

env:
  browser: true
  node: true
  es2022: true

parserOptions:
  project: './tsconfig.json'

extends:
  - 'airbnb'
  - 'airbnb-typescript'

rules:
  'max-len':
    - 'error'
    - 'code': 120
  'no-param-reassign': 'off'
  'import/prefer-default-export': 'off'
  'no-console': 'off'
  'react/jsx-sort-props': 'error'
  'react/require-default-props': 'off'
  'react/function-component-definition': 'off'
  'import/extensions': 'off'
  'object-curly-newline': 'off'
